climate_kb = {
    "entities": [
        "University of Adelaide",
        "Australian Burden of Disease Database",
        "European Heart Journal",
        "Intergovernmental Panel on Climate Change",
        "IPCC",
        "National Aeronautics and Space Administration",
        "NASA",
        "National Oceanic and Atmospheric Administration",
        "NOAA",
        "United Nations Framework Convention on Climate Change",
        "UNFCCC",
        "World Meteorological Organization",
        "WMO",
        "International Energy Agency",
        "IEA",
        "Environmental Protection Agency",
        "EPA",
        "European Environment Agency",
        "EEA",
        "Climate Action Network",
        "CAN",
        "United Nations Environment Programme",
        "UNEP",
        "Global Carbon Project",
        "The Royal Society",
        "Met Office (UK)",
        "Carbon Disclosure Project",
        "CDP",
        "Australian Antarctic Program Partnership",
        "AAPP",
        "University of Tasmania",
        "University of California, Los Angeles",
        "UCLA",
        "Department of Environment, Food and Agriculture",
        "Defa",
        "Geological Survey of Denmark and Greenland",
        "Organisation for Economic Co-operation and Development",
        "OECD",
        "Petersberg Climate Dialogue",
        "2023 Dubai Climate Summit",
        "Copernicus Climate Change Service",
        "COP30",
        ],
    "facts": [
        "Global temperatures have risen by 1.1 degrees Celsius since pre-industrial times",
        "CO2 is the primary greenhouse gas emitted through human activities",
        "Sea levels are rising at 3.3 mm per year",
        "The Amazon rainforest is a major carbon sink",
        "The Paris Agreement aims to limit warming to 1.5°C",
        "For each 1°C increase in sea temperature, green sea turtles lay eggs approximately 6 days earlier",
        "Incubation temperature in turtles determines sex: higher = female, lower = male",
        "Arctic sea ice had its weakest winter buildup in 47 years of record-keeping as of 2025",
        "The Arctic region is warming four times faster than the global average",
        "Melting Arctic sea ice impacts global weather patterns by weakening the jet stream",
        "Melting Arctic sea ice contributes to stronger and more prolonged weather systems",
        "Methane is approximately 80 times more potent than CO₂ over a 20-year period in terms of global warming potential",
        "Methane has contributed around 0.5°C to observed global warming since preindustrial times",
        "The UK's territorial greenhouse gas emissions were 371 MtCO2e in 2024, a 4% decrease from 2023",
        "UK emissions in 2024 were 54% lower than in 1990, according to DESNZ",
        "Electricity supply emissions in the UK dropped by 15% in 2024 due to decreased gas and coal use",
        "Industrial emissions in the UK fell by 9% in 2024",
        "Carbon dioxide (CO2) accounted for 78% of the UK’s total greenhouse gas emissions in 2024",
        "Honeybee colonies in the U.S. are projected to decline by up to 70% in 2025, according to Washington State University",
        "Honeybee colony losses in the U.S. have averaged 40% to 50% annually over the past decade",
        "Earth lost over 2,614 gigatonnes of soil moisture between 2000 and 2016, more than Greenland's ice sheet loss in the same period",
        "Soil moisture loss between 2000–2002 alone contributed to a 1.95 mm/year sea level rise, compared to 0.8 mm/year from Greenland's ice loss (2002–2006)",
        "Rising VPD, driven by global warming, accelerates water loss from soil and makes recovery harder",
        "Global warming accelerates the water cycle, increasing both droughts and extreme rainfall events",
        "Rainfall becomes less frequent but more intense, contributing to flash floods and infrastructure damage",
        "Warmer oceans contribute to larger and more destructive hurricanes and cyclones",
        "The population of Bewick’s swans returning to WWT Slimbridge has declined by 86% over the past 50 years",
        "Bewick’s swans face additional threats from toxic lead poisoning and illegal shooting during migration",
        "Hot weather increases cardiovascular strain because the heart must work harder to help cool the body",
        "Projections about future cardiovascular disease burdens depend on greenhouse gas emission scenarios outlined by the Intergovernmental Panel on Climate Change (IPCC)",
        "Research on cardiovascular risk and hot weather was published in the European Heart Journal",
        "The annual daily minimum sea ice extent on March 1, 2025, was the third-lowest on record",
        "Setting ambitious targets to cut greenhouse gas emissions results in a net gain to global GDP by 2040",
        "The net gain to global GDP is estimated at 0.23% by 2040",
        "By 2050, advanced economies could see a 60% increase in GDP per capita growth compared to 2025",
        "Extreme weather could reduce Europe’s GDP by 1% before mid-century and 2.3% annually by 2050",
        "Florida receives about 8% of its electricity from solar power; most of its power still comes from fossil gas",
        "A 2022 Mason-Dixon poll found 84% of Florida voters, including 76% of Republicans, supported net metering",
        "2024 was the hottest year on record, according to NASA",
        "Global sea levels rose by 0.59 cm in 2024, higher than the expected 0.43 cm",
        "Sea level rise has more than doubled since satellite measurements began in 1993",
        "Average global sea level has risen by about 10 cm (3.93 inches) from 1993 to 2023",
        "Mountain glaciers are melting more than twice as fast as in the early 2000s due to climate change",
        "From 2000 to 2011, glaciers lost 255 billion tons of ice annually",
        "From 2011 to 2020, the loss increased to 346 billion tons per year",
        "In 2023, glacier melt hit a record 604 billion tons of ice lost",
        "Since 2000, the world's glaciers have lost over 7 trillion tons of ice",
        "Accelerated climate action could boost global GDP by 0.2% by 2040 compared to current policies",
        "Unclear or delayed climate policies could reduce global GDP by 0.75% by 2030",
        "China’s glacier area has shrunk by 26% since 1960 due to rapid global warming",
        "7,000 small glaciers in China have completely disappeared since 1960",
        "China's total glacier area was around 46,000 sq km in 2020, down from ~59,000 sq km in 1960–1980",
        "Carbon dioxide levels are at their highest in 800,000 years",
        "Ocean temperatures and sea levels reached record highs in 2024",
        "There were at least 151 unprecedented extreme weather events in 2024",
        "El Niño (June 2023–June 2024) contributed to record heat alongside human-induced warming",
        "Glaciers lost 450 gigatons of mass in 2024 alone",
        "Mountain glaciers are now one of the largest contributors to sea level rise",
        "Melted mountain glaciers caused 18 mm of sea level rise between 2000–2023, about 1 mm/year",
        "Each millimeter of sea level rise can expose up to 300,000 people to annual flooding",
        "Glaciers in Eastern Africa have lost 80% of their mass; between one-third and one-half of Andes glaciers have melted since 1998",
        "Glaciers in the Alps and Pyrenees have shrunk by about 40% in recent decades",
        "Mountain regions supply 60% of the world’s freshwater but are among the most food-insecure",
        "More than a third (34%) of Antarctic ice shelves—about 500,000 sq km—could collapse if global temperatures rise by 4°C above pre-industrial levels",
        "67% of ice shelf area on the Antarctic Peninsula would be at risk of destabilization under a 4°C warming scenario",
        "Limiting warming to 2°C would halve the area of Antarctic ice shelf collapse risk compared to 4°C",
        "Mountain glaciers have lost more than 6,500 billion tonnes of ice since 2000, about 5% of their total mass",
        "Glaciers are melting 34% faster over the past decade than they did between 2000–2011",
        "From 2000 to 2023, non-polar glaciers lost an average of 270 billion tonnes of ice per year",
        "Between 2023 and 2024 alone, glaciers lost approximately 550 billion tonnes of ice",
        "If all mountain glaciers melted, global sea levels would rise by 32 cm (13 in)",
        "Central Europe has lost 39% of its glacier ice in just over 20 years",
        "Since 1900, global sea levels have risen more than 20 cm, half of that increase occurring since the early 1990s",
        "Ocean acidity has increased by about 30% since the Industrial Revolution due to increased absorption of atmospheric CO2",
        "Ocean acidification reduces the availability of carbonate ions, which are essential for marine organisms like corals and shellfish to build their skeletons and shells",
        "Coral reefs worldwide have experienced significant bleaching and structural weakening due to the combined effects of warming and acidification",
        "Ocean acidification negatively impacts plankton species, which form the base of marine food webs and play a key role in carbon cycling",
        "Research indicates that continued CO2 emissions could reduce the saturation state of carbonate minerals, threatening the survival of many calcifying organisms by 2100",
        "The pH of surface ocean waters has decreased from about 8.2 to 8.1 since pre-industrial times, representing a 30% increase in acidity"
    ]
}